SunsetJobCreator = SunsetJobCreator or {}

--- Reusable stage blocks for the Job Creator UI (Lego modules).
--- Each module merges variables/locations/pools/stages into a job definition.
SunsetJobCreator.Modules = {
    {
        id = 'mod_init_level',
        icon = '📈',
        category = 'setup',
        label = 'Start: sarcini după level',
        description = 'La începutul shift-ului setează câte task-uri trebuie (total) din level-ul jobului și resetează contorul (done) la 0.',
        hint = 'Pune primul pas. Conectează „Dacă reușește” la următorul modul (ex: du-te la hub).',
        variables = { done = 0, total = 5 },
        stages = {
            {
                id = 'init',
                type = 'scale_from_level',
                label = 'Calculează număr sarcini',
                var = 'total',
                resetVar = 'done',
                base = 5,
                perLevel = 1,
                max = 12,
                onSuccess = 'next',
            },
        },
    },
    {
        id = 'mod_goto_hub',
        icon = '📍',
        category = 'movement',
        label = 'Du-te la hub (loc fix)',
        description = 'GPS + marker la un loc fix din tab Locuri. Jucătorul intră în zonă → avansează automat.',
        hint = 'Creează locul „hub” în tab Locuri înainte, sau schimbă location în editor după inserare.',
        locations = {
            hub = { x = 0.0, y = 0.0, z = 0.0, radius = 8.0, zTolerance = 6.0, label = 'Hub job' },
        },
        stages = {
            {
                id = 'to_hub',
                type = 'goto_zone',
                label = 'Mergi la punctul de start',
                location = 'hub',
                message = 'Urmează markerul',
                onSuccess = 'next',
            },
        },
    },
    {
        id = 'mod_vehicle_chain',
        icon = '🚚',
        category = 'vehicles',
        label = 'Spawn camion + remorcă',
        description = 'Apare vehiculul, atașează remorca, jucătorul trebuie să fie în mașină.',
        hint = 'Adaugă loc „depot” în tab Locuri sau folosește 📍 Pune loc aici.',
        variables = { truck = 0, trailer = 0 },
        locations = {
            depot = { x = 0.0, y = 0.0, z = 0.0, radius = 12.0, zTolerance = 6.0, label = 'Depozit vehicule' },
        },
        stages = {
            {
                id = 'spawn_truck',
                type = 'spawn_vehicle',
                label = 'Ia camionul',
                model = 'phantom',
                location = 'depot',
                warp = true,
                storeAs = 'truck',
                onSuccess = 'attach_trailer',
            },
            {
                id = 'attach_trailer',
                type = 'attach_trailer',
                label = 'Atașează remorca',
                vehicleVar = 'truck',
                trailerModel = 'trailers2',
                location = 'depot',
                onSuccess = 'enter_truck',
            },
            {
                id = 'enter_truck',
                type = 'enter_vehicle',
                label = 'Intră în camion',
                vehicleVar = 'truck',
                message = 'Intră în vehicul',
                onSuccess = 'next',
            },
        },
    },
    {
        id = 'mod_delivery_loop',
        icon = '🔄',
        category = 'loop',
        label = 'Loop livrări (random → E → plată)',
        description = 'Alege destinație din pool → du-te acolo → apasă E → +1 done → plată → dacă done < total, repetă.',
        hint = 'Necesită pool „deliveries” cu puncte în tab Locuri. Leagă ultimul pas (branch) înapoi la pick.',
        variables = { done = 0, total = 3, target = 0 },
        pools = {
            deliveries = {},
        },
        stages = {
            {
                id = 'pick_target',
                type = 'pick_random',
                label = 'Destinație nouă',
                pool = 'deliveries',
                storeAs = 'target',
                onSuccess = 'to_target',
            },
            {
                id = 'to_target',
                type = 'goto_zone',
                label = 'Du-te la livrare',
                locationVar = 'target',
                message = 'Livrare — urmează GPS',
                onSuccess = 'deliver',
            },
            {
                id = 'deliver',
                type = 'zone_interact',
                label = 'Livrează (E)',
                locationVar = 'target',
                message = 'Apasă {key} pentru a livra',
                actions = { { type = 'increment', var = 'done', value = 1 } },
                onSuccess = 'pay_leg',
            },
            {
                id = 'pay_leg',
                type = 'give_reward',
                label = 'Plată livrare',
                onSuccess = 'check_done',
            },
            {
                id = 'check_done',
                type = 'branch',
                label = 'Mai sunt livrări?',
                condition = { var = 'done', op = '<', valueRef = 'total' },
                ifTrue = 'pick_target',
                ifFalse = 'next',
            },
        },
    },
    {
        id = 'mod_skill_spot',
        icon = '🎯',
        category = 'gameplay',
        label = 'Spot skill check (vein / minigame)',
        description = 'Alege punct random din pool → du-te → minigame reflex (bara verde) → plată → +1 contor → loop.',
        hint = 'Pool „spots” = vena de minereu / punct de lucru. Conectează branch înapoi la pick_spot.',
        variables = { done = 0, total = 6, spot = 0 },
        pools = {
            spots = {},
        },
        stages = {
            {
                id = 'pick_spot',
                type = 'pick_random',
                label = 'Alege loc de lucru',
                pool = 'spots',
                storeAs = 'spot',
                onSuccess = 'to_spot',
            },
            {
                id = 'to_spot',
                type = 'goto_zone',
                label = 'Mergi la loc',
                locationVar = 'spot',
                message = 'Urmează markerul',
                onSuccess = 'skill',
            },
            {
                id = 'skill',
                type = 'skill_check',
                label = 'Minigame reflex',
                locationVar = 'spot',
                windowMs = 1800,
                message = 'Apasă {key} când bara e verde!',
                onSuccess = 'pay_spot',
                onFailure = 'pick_spot',
            },
            {
                id = 'pay_spot',
                type = 'give_reward',
                label = 'Plată task',
                onSuccess = 'inc_done',
            },
            {
                id = 'inc_done',
                type = 'set_variable',
                label = '+1 la done',
                actions = { { type = 'increment', var = 'done', value = 1 } },
                onSuccess = 'check_done',
            },
            {
                id = 'check_done',
                type = 'branch',
                label = 'Mai sunt task-uri?',
                condition = { var = 'done', op = '<', valueRef = 'total' },
                ifTrue = 'pick_spot',
                ifFalse = 'next',
            },
        },
    },
    {
        id = 'mod_chop_tree',
        icon = '🪓',
        category = 'gameplay',
        label = 'Taie copac (spawn + chop)',
        description = 'Spawn copac la loc random → animație topor → plată → loop cu cooldown pe pool.',
        hint = 'Pool „trees”. Pune coordonate cu 📍. Model copac schimbabil în pasul spawn.',
        variables = { done = 0, total = 5, tree = 0 },
        pools = {
            trees = {},
        },
        stages = {
            {
                id = 'pick_tree',
                type = 'pick_random',
                label = 'Alege copac',
                pool = 'trees',
                storeAs = 'tree',
                respectCooldown = true,
                onSuccess = 'spawn_tree',
            },
            {
                id = 'spawn_tree',
                type = 'spawn_prop',
                label = 'Apare copacul',
                model = 'prop_tree_pine_02',
                locationVar = 'tree',
                storeAs = 'treeProp',
                onSuccess = 'to_tree',
            },
            {
                id = 'to_tree',
                type = 'goto_zone',
                label = 'Mergi la copac',
                locationVar = 'tree',
                message = 'Taie copacul',
                onSuccess = 'chop',
            },
            {
                id = 'chop',
                type = 'chop_prop',
                label = 'Taie (topor)',
                locationVar = 'tree',
                propVar = 'treeProp',
                model = 'prop_tree_pine_02',
                swings = 5,
                durationMs = 6000,
                message = 'Apasă {key} pentru a tăia',
                regenerateSec = 45,
                onSuccess = 'pay_log',
            },
            {
                id = 'pay_log',
                type = 'give_reward',
                label = 'Plată lemn',
                onSuccess = 'inc_done',
            },
            {
                id = 'inc_done',
                type = 'set_variable',
                label = '+1 lemn',
                actions = { { type = 'increment', var = 'done', value = 1 } },
                onSuccess = 'check_done',
            },
            {
                id = 'check_done',
                type = 'branch',
                label = 'Mai sunt copaci?',
                condition = { var = 'done', op = '<', valueRef = 'total' },
                ifTrue = 'pick_tree',
                ifFalse = 'next',
            },
        },
    },
    {
        id = 'mod_progress_work',
        icon = '⏳',
        category = 'gameplay',
        label = 'Muncă cu bară de progres',
        description = 'Du-te la loc → ține E / bară de progres câteva secunde → plată. Bun pentru scan, încărcare, plantat.',
        hint = 'Poți folosi loc fix sau variabilă target.',
        variables = { done = 0, total = 4, workSpot = 0 },
        pools = {
            work_spots = {},
        },
        stages = {
            {
                id = 'pick_work',
                type = 'pick_random',
                label = 'Alege punct de muncă',
                pool = 'work_spots',
                storeAs = 'workSpot',
                onSuccess = 'to_work',
            },
            {
                id = 'to_work',
                type = 'goto_zone',
                label = 'Mergi la punct',
                locationVar = 'workSpot',
                message = 'Urmează markerul',
                onSuccess = 'work',
            },
            {
                id = 'work',
                type = 'progress',
                label = 'Lucrează (bară)',
                locationVar = 'workSpot',
                durationMs = 5000,
                message = 'Apasă {key} și așteaptă',
                onSuccess = 'pay_work',
            },
            {
                id = 'pay_work',
                type = 'give_reward',
                label = 'Plată',
                onSuccess = 'inc_done',
            },
            {
                id = 'inc_done',
                type = 'set_variable',
                label = '+1 task',
                actions = { { type = 'increment', var = 'done', value = 1 } },
                onSuccess = 'check_done',
            },
            {
                id = 'check_done',
                type = 'branch',
                label = 'Continuă?',
                condition = { var = 'done', op = '<', valueRef = 'total' },
                ifTrue = 'pick_work',
                ifFalse = 'next',
            },
        },
    },
    {
        id = 'mod_sell_finale',
        icon = '💰',
        category = 'finish',
        label = 'Final: vinde la buyer + bonus',
        description = 'Du-te la punctul de vânzare → E → bonus plată mare → termină jobul.',
        hint = 'Creează loc „sell” în tab Locuri.',
        locations = {
            sell = { x = 0.0, y = 0.0, z = 0.0, radius = 5.0, zTolerance = 5.0, label = 'Cumpărător' },
        },
        stages = {
            {
                id = 'to_sell',
                type = 'goto_zone',
                label = 'Mergi la vânzare',
                location = 'sell',
                message = 'Vinde marfa',
                onSuccess = 'sell',
            },
            {
                id = 'sell',
                type = 'zone_interact',
                label = 'Vinde (E)',
                location = 'sell',
                message = 'Apasă {key} pentru a vinde',
                onSuccess = 'bonus',
            },
            {
                id = 'bonus',
                type = 'give_reward',
                label = 'Bonus final',
                pay = 150,
                xp = 30,
                onSuccess = 'finish',
            },
            {
                id = 'finish',
                type = 'complete',
                label = 'Shift complet',
            },
        },
    },
    {
        id = 'mod_return_vehicle',
        icon = '🏁',
        category = 'finish',
        label = 'Returnează vehiculul + termină',
        description = 'Adu mașina la depozit, șterge vehiculul, termină shift-ul.',
        hint = 'Folosește același loc „depot” ca la spawn.',
        locations = {
            depot = { x = 0.0, y = 0.0, z = 0.0, radius = 10.0, zTolerance = 6.0, label = 'Return vehicul' },
        },
        stages = {
            {
                id = 'return_truck',
                type = 'return_vehicle',
                label = 'Înapoi cu vehiculul',
                vehicleVar = 'truck',
                location = 'depot',
                message = 'Parchează vehiculul',
                onSuccess = 'delete_truck',
            },
            {
                id = 'delete_truck',
                type = 'delete_vehicle',
                label = 'Elimină vehicul',
                vehicleVar = 'truck',
                onSuccess = 'finish',
            },
            {
                id = 'finish',
                type = 'complete',
                label = 'Shift complet',
            },
        },
    },
}

SunsetJobCreator.ModuleCategories = {
    setup = 'Pornire',
    movement = 'Mișcare',
    vehicles = 'Vehicule',
    loop = 'Bucle (repetări)',
    gameplay = 'Gameplay',
    finish = 'Final',
}

function SunsetJobCreator.GetModules()
    return SunsetJobCreator.Modules
end

function SunsetJobCreator.GetModuleCategories()
    return SunsetJobCreator.ModuleCategories
end
