Sunset = Sunset or {}

Sunset.CraftingStations = {
    public_bench = {
        label = 'Workbench',
        coords = vector3(1087.35, -2003.25, 31.08),
        blip = { sprite = 566, color = 0, scale = 0.75 },
        marker = { 200, 200, 200 },
        access = 'public',
    },
    police_armory = {
        label = 'LSPD Armory Craft',
        coords = vector3(452.35, -980.12, 30.69),
        marker = { 0, 100, 200 },
        access = 'faction',
        faction = 'police',
        minGrade = 1,
    },
    cartel_lab = {
        label = 'Cartel Lab',
        coords = vector3(1396.2, 1138.5, 114.33),
        marker = { 180, 0, 0 },
        access = 'faction',
        faction = 'sunset_cartel',
        minGrade = 1,
        illegal = true,
    },
    syndicate_bench = {
        label = 'Syndicate Workshop',
        coords = vector3(-1518.5, 847.2, 181.59),
        marker = { 80, 0, 120 },
        access = 'faction',
        faction = 'night_syndicate',
        minGrade = 1,
        illegal = true,
    },
}

Sunset.CraftingRecipes = {
    bandage = {
        label = 'Bandage',
        station = 'public_bench',
        time = 4000,
        inputs = { cloth = 2 },
        output = { item = 'bandage', count = 1 },
    },
    lockpick = {
        label = 'Lockpick',
        station = 'public_bench',
        time = 6000,
        inputs = { metal_scrap = 2, plastic = 1 },
        output = { item = 'lockpick', count = 1 },
    },
    repairkit = {
        label = 'Repair Kit',
        station = 'public_bench',
        time = 8000,
        inputs = { metal_scrap = 3, plastic = 2 },
        output = { item = 'repairkit', count = 1 },
    },
    police_bandage = {
        label = 'EMS Supply Bandage',
        station = 'police_armory',
        time = 3000,
        inputs = { cloth = 1 },
        output = { item = 'bandage', count = 2 },
        faction = 'police',
        minGrade = 1,
    },
    cartel_pouch = {
        label = 'Sealed Pouch',
        station = 'cartel_lab',
        time = 10000,
        inputs = { chemicals = 2, plastic = 1 },
        output = { item = 'sealed_pouch', count = 1 },
        faction = 'sunset_cartel',
        minGrade = 1,
        illegal = true,
    },
    syndicate_shiv = {
        label = 'Shiv',
        station = 'syndicate_bench',
        time = 7000,
        inputs = { metal_scrap = 2, cloth = 1 },
        output = { item = 'shiv', count = 1 },
        faction = 'night_syndicate',
        minGrade = 1,
        illegal = true,
    },
    syndicate_ammo = {
        label = '9mm Rounds',
        station = 'syndicate_bench',
        time = 12000,
        inputs = { metal_scrap = 4, gunpowder = 2 },
        output = { item = 'ammo_9mm', count = 1 },
        faction = 'night_syndicate',
        minGrade = 2,
        illegal = true,
    },
}
