Sunset = Sunset or {}

--- Static help catalog. Runtime filtering happens in sunset_help server.
Sunset.HelpAdminDescriptions = {
    kick = 'Kick a player from the server',
    ban = 'Permanently ban a player (player ID required)',
    unban = 'Remove a ban by player ID or license:xxx',
    tp = 'Teleport to a player or x y z coordinates',
    bring = 'Bring a player to your location',
    ['goto'] = 'Teleport to a player',
    car = 'Spawn a vehicle by model name',
    dv = 'Delete your current vehicle',
    heal = 'Heal yourself or another player',
    revive = 'Revive a downed player',
    arespawn = 'Open spawn menu for a player or hospital respawn',
    noclip = 'Toggle noclip mode',
    god = 'Toggle god mode',
    announce = 'Send a server-wide announcement',
    setadmin = 'Set admin level for an account',
    coords = 'Show your position — /coords, /getpos, /pos (add v4 for vector4). Tip: stand here, then /setcp [name]',
    hudexport = 'Export HUD layout JSON',
    setcp = 'Save your current position as a named checkpoint',
    delcp = 'Delete a saved admin checkpoint',
    gotocp = 'Teleport to a saved admin checkpoint by name',
    gotoloc = 'Teleport to a predefined world location by id or name',
    speed = 'Boost vehicle engine power while driving (multiplier)',
    dealershipadmin = 'Manage dealership stock, prices, availability and catalog entries',
    setjob = 'Set a player civilian job (trucker, fisherman, etc.)',
    setfaction = 'Assign a player to a faction with grade',
    givecar = 'Give a vehicle to a player (stored in garage)',
    giveitem = 'Give inventory items to a player: /giveitem [id] [item] [count]',
    givegun = 'Give a weapon to a player: /givegun [id] [weapon] [ammo]',
    setleader = 'Grant faction leader permissions to a member',
    removeleader = 'Revoke faction leader role from a member',
    acreatehouse = 'Create a house at your current position: price, interior, minimum level, name',
    ahouseedit = 'Edit a house price, level, name, sale status, or enabled status',
    astats = 'Inspect an online player\'s character, economy and job progression',
    setstat = 'Set an online player stat: cash, bank, level, rp, rob, paydays, playtime, premium, hunger, thirst, stress',
    setsc = 'Set Sunset Coins for a player: /setsc [id] [amount]',
    setpp = 'Alias for /setsc — set Sunset Coins (premium points)',
    setrob = 'Set a player robbery points: /setrob [id] [value]',
    setjobstat = 'Set civilian job progress: /setjobstat [id] [job] [xp|level|tasks|earned] [value]',
}

Sunset.HelpGeneralEntries = {
    { cmd = '/help', desc = 'Open this command guide' },
    { cmd = '/stats', desc = 'Open character statistics, level and Respect Point progress' },
    { cmd = '/buylevel', desc = 'Spend the required RP and money to purchase your next level' },
    { cmd = '/me [text]', desc = 'Roleplay action visible to nearby players' },
    { cmd = '/do [text]', desc = 'Describe the scene or environment' },
    { cmd = 'M', desc = 'Player menu — stats, vehicle, job, settings' },
    { cmd = 'I', desc = 'Inventory' },
    { cmd = 'P', desc = 'Phone' },
    { cmd = 'F10', desc = 'Hold for player list' },
    { cmd = 'TAB / mouse wheel', desc = 'Weapon wheel / cycle weapons' },
    { cmd = 'E', desc = 'Interact — shops, ATMs, faction HQ, crafting' },
    { cmd = '/inventory', desc = 'Open inventory' },
    { cmd = '/phone', desc = 'Toggle phone' },
    { cmd = '/documents', desc = 'View documents panel' },
    { cmd = '/id', desc = 'Show ID card' },
    { cmd = '/licenses', desc = 'Show licenses' },
    { cmd = '/v', desc = 'Personal vehicle garage' },
    { cmd = '/garage', desc = 'Garage panel' },
    { cmd = '/dealership', desc = 'Browse vehicles at Premium Deluxe Motorsport' },
    { cmd = '2', desc = 'Start or stop the vehicle engine manually' },
    { cmd = 'K', desc = 'Toggle vehicle seatbelt' },
    { cmd = '/properties', desc = 'Browse houses, prices, owners, rent and access' },
    { cmd = '/sethome [id]', desc = 'Set spawn home at a house you own or rent' },
    { cmd = '/renthouse', desc = 'Explains how to rent; stand at a house and press E' },
    { cmd = '/unrent', desc = 'End your active house rental (job and faction stay)' },
    { cmd = '/houselock [id]', desc = 'Owner: lock or unlock your house' },
    { cmd = '/houserent [price|off] [id]', desc = 'Owner: accept renters and set payday rent' },
    { cmd = '/housemaxrenters [1-10] [id]', desc = 'Owner: set available rental slots' },
    { cmd = '/houseinterior [name] [id]', desc = 'Owner: change house interior' },
    { cmd = '/houseinteriors', desc = 'List available house interiors' },
    { cmd = '/hdescription [text|off]', desc = 'Owner: set the floating house message for renters and visitors' },
    { cmd = '/houserenters [id]', desc = 'Owner: list active renters' },
    { cmd = '/housekickrenter [character id] [house id]', desc = 'Owner: remove a renter' },
    { cmd = '/sellhouse [id] confirm', desc = 'Owner: sell house back for 70% of its price' },
    { cmd = '/emotes', desc = 'Open emotes panel' },
    { cmd = '/e [name]', desc = 'Play an emote' },
    { cmd = '/stopemote', desc = 'Stop current emote' },
    { cmd = '/handsup', desc = 'Raise hands' },
    { cmd = '/jobs', desc = 'Open jobs panel' },
    { cmd = '/work [cancel]', desc = 'Start civilian job shift or cancel current shift' },
    { cmd = '/skills', desc = 'View job skill levels' },
    { cmd = '/pass', desc = 'Open Sunset Pass rewards track' },
    { cmd = '/missions', desc = 'Open Sunset Pass missions' },
    { cmd = '/crafting', desc = 'Mark the nearest crafting station available to your faction' },
    { cmd = '/jobhelp', desc = 'Help text for your civilian job' },
    { cmd = '/fish', desc = 'Cast and play the fishing reaction challenge at a fishing spot' },
    { cmd = '/sellfish', desc = 'Mark the Fish Buyer or sell carried fish inside the yellow marker' },
    { cmd = '/recovertrailer', desc = 'Right and reattach an overturned assigned Trucker trailer' },
    { cmd = '/quitjob', desc = 'Quit civilian job at Job Center' },
    { cmd = '/faction', desc = 'Faction rank, salary, and your commands' },
    { cmd = '/factions', desc = 'Browse factions and Discord/website application status' },
    { cmd = '/acceptfaction', desc = 'Accept a pending invitation from an admin-appointed faction leader' },
    { cmd = '/declinefaction', desc = 'Decline a pending faction invitation' },
    { cmd = '/leavefaction', desc = 'Leave your faction (job stays)' },
    { cmd = '/quitfaction', desc = 'Alias for /leavefaction (civilian job stays)' },
    { cmd = '/factionquit', desc = 'Alias for /leavefaction (civilian job stays)' },
    { cmd = '/quitgroup', desc = 'Alias for /leavefaction (civilian job stays)' },
    { cmd = '/duty', desc = 'Toggle on/off duty at faction HQ' },
    { cmd = '/clan', desc = 'Open your clan page — create, members, tag style, and management' },
    { cmd = '/clans', desc = 'Browse all player-created clans on the server' },
    { cmd = '/acceptclan', desc = 'Accept a pending clan invitation' },
    { cmd = '/declineclan', desc = 'Decline a pending clan invitation' },
    { cmd = '/f [message]', desc = 'Faction chat' },
    { cmd = '/service [type] [msg]', desc = 'Request taxi, medic, fire, or mechanic' },
    { cmd = '/relook', desc = 'Re-open character appearance editor' },
    { cmd = '/respawn', desc = 'Respawn at hospital when downed (after bleedout timer)' },
    { cmd = '/spawnmenu', desc = 'Open spawn location selector without reconnecting' },
    { cmd = '/hudedit', desc = 'Move HUD panels' },
    { cmd = '/hudreset', desc = 'Reset HUD layout to default' },
    { cmd = '/rob', desc = 'Start a marked luxury-store robbery (requires 1 rob point, a lockpick and enough on-duty police)' },
    { cmd = '[E] robbery', desc = 'Start robbery, route the security circuit, smash displays, then escape 300m' },
    { cmd = '[E] fence', desc = 'Sell stolen watches and jewelry to the dockside fence' },
}

--- Command usage for chat preflight (permission + argument hints before execution).
Sunset.CommandUsage = {
    kick = { usage = '/kick [server id] [reason]', minArgs = 1 },
    ban = { usage = '/ban [server id] [reason]', minArgs = 1 },
    unban = { usage = '/unban [player id or license:xxx]', minArgs = 1 },
    tp = { usage = '/tp [server id] or /tp [x] [y] [z]', minArgs = 1 },
    bring = { usage = '/bring [server id]', minArgs = 1 },
    ['goto'] = { usage = '/goto [server id]', minArgs = 1 },
    car = { usage = '/car [model]', minArgs = 0 },
    dv = { usage = '/dv', minArgs = 0 },
    heal = { usage = '/heal [server id]', minArgs = 0 },
    revive = { usage = '/revive [server id]', minArgs = 0 },
    arespawn = { usage = '/arespawn [server id] or /arespawn [server id] hospital', minArgs = 1 },
    noclip = { usage = '/noclip', minArgs = 0 },
    god = { usage = '/god', minArgs = 0 },
    announce = { usage = '/announce [message]', minArgs = 1 },
    setadmin = { usage = '/setadmin [username or id] [level 0-5]', minArgs = 2 },
    coords = { usage = '/coords [v4]', minArgs = 0 },
    hudexport = { usage = '/hudexport', minArgs = 0 },
    setcp = { usage = '/setcp [name]', minArgs = 1 },
    delcp = { usage = '/delcp [name]', minArgs = 1 },
    gotocp = { usage = '/gotocp [name]', minArgs = 1 },
    gotoloc = { usage = '/gotoloc [location id or name]', minArgs = 1 },
    speed = { usage = '/speed [multiplier]', minArgs = 1 },
    dealershipadmin = { usage = '/dealershipadmin', minArgs = 0 },
    setjob = { usage = '/setjob [server id] [job]', minArgs = 2 },
    setfaction = { usage = '/setfaction [server id] [faction] [grade]', minArgs = 2 },
    givecar = { usage = '/givecar [server id] [model]', minArgs = 2 },
    giveitem = { usage = '/giveitem [server id] [item] [count]', minArgs = 2 },
    givegun = { usage = '/givegun [server id] [weapon] [ammo]', minArgs = 2 },
    setleader = { usage = '/setleader [server id] [faction]', minArgs = 2 },
    removeleader = { usage = '/removeleader [server id] [faction]', minArgs = 2 },
    acreatehouse = { usage = '/acreatehouse [price] [interior] [min level] [name]', minArgs = 4 },
    ahouseedit = { usage = '/ahouseedit [house id] [field] [value]', minArgs = 3 },
    astats = { usage = '/astats [server id]', minArgs = 1 },
    setstat = { usage = '/setstat [server id] [stat] [value]', minArgs = 3 },
    setrob = { usage = '/setrob [server id] [value]', minArgs = 2 },
    setjobstat = { usage = '/setjobstat [server id] [job] [stat] [value]', minArgs = 4 },
    me = { usage = '/me [action text]', minArgs = 1 },
    ['do'] = { usage = '/do [scene text]', minArgs = 1 },
    help = { usage = '/help', minArgs = 0 },
    stats = { usage = '/stats', minArgs = 0 },
    buylevel = { usage = '/buylevel', minArgs = 0 },
    inventory = { usage = '/inventory', minArgs = 0 },
    phone = { usage = '/phone', minArgs = 0 },
    v = { usage = '/v', minArgs = 0 },
    garage = { usage = '/garage', minArgs = 0 },
    properties = { usage = '/properties', minArgs = 0 },
    emotes = { usage = '/emotes', minArgs = 0 },
    e = { usage = '/e [emote name]', minArgs = 1 },
    stopemote = { usage = '/stopemote', minArgs = 0 },
    jobs = { usage = '/jobs', minArgs = 0 },
    work = { usage = '/work [cancel]', minArgs = 0 },
    skills = { usage = '/skills', minArgs = 0 },
    pass = { usage = '/pass', minArgs = 0 },
    missions = { usage = '/missions', minArgs = 0 },
    duty = { usage = '/duty', minArgs = 0 },
    faction = { usage = '/faction', minArgs = 0 },
    factions = { usage = '/factions', minArgs = 0 },
    clan = { usage = '/clan', minArgs = 0 },
    clans = { usage = '/clans', minArgs = 0 },
    acceptclan = { usage = '/acceptclan', minArgs = 0 },
    declineclan = { usage = '/declineclan', minArgs = 0 },
    dealership = { usage = '/dealership', minArgs = 0 },
    relook = { usage = '/relook', minArgs = 0 },
    hudedit = { usage = '/hudedit', minArgs = 0 },
    hudreset = { usage = '/hudreset', minArgs = 0 },
    rob = { usage = '/rob', minArgs = 0 },
    fish = { usage = '/fish', minArgs = 0 },
    sellfish = { usage = '/sellfish', minArgs = 0 },
    getpos = { usage = '/getpos', minArgs = 0 },
    pos = { usage = '/pos', minArgs = 0 },
}

Sunset.HelpDispatchEntries = {
    { cmd = '/calls', desc = 'Open service calls panel (on duty)' },
    { cmd = '/servicecalls', desc = 'List open calls for your duty role' },
    { cmd = '/accept [type] [id]', desc = 'Accept a service call' },
    { cmd = '/cancel [type] [id]', desc = 'Cancel a service call' },
}

Sunset.HelpFireEntries = {
    { cmd = '/fd', desc = 'Full LSFD how-to in chat' },
    { cmd = '/firestart', desc = 'Start a vehicle fire if none is active (on duty)' },
    { cmd = '/firecalls', desc = 'List fires and set GPS to the first one' },
    { cmd = '/calls', desc = 'Accept civilian /service fire calls' },
    { cmd = 'Extinguisher', desc = 'Walk up to the burning wreck — spray LMB until it dies' },
    { cmd = '[E] garage', desc = 'Spawn the firetruk at Fire Station Garage' },
}

--- Client-registered commands (not always visible to server GetRegisteredCommands).
Sunset.ClientCommands = {}
local function markClientCommand(name)
    if name and name ~= '' then
        Sunset.ClientCommands[string.lower(name)] = true
    end
end

for _, row in ipairs(Sunset.HelpGeneralEntries or {}) do
    markClientCommand(row.cmd and row.cmd:match('^/(%w+)'))
end
for _, list in ipairs({ Sunset.HelpDispatchEntries, Sunset.HelpFireEntries }) do
    for _, row in ipairs(list or {}) do
        markClientCommand(row.cmd and row.cmd:match('^/(%w+)'))
    end
end

for _, name in ipairs({
    'noclip', 'god', 'coords', 'getpos', 'pos', 'car', 'dv', 'hudexport',
    'fine', 'cuff', 'uncuff', 'repairveh', 'fare', 'finvite', 'accept', 'fpromote',
    'fgiverank', 'funinvite', 'fwarn', 'fmotd', 'fmembers', 'sellpouch', 'fence',
    'pd', 'fd', 'pdgarage', 'su', 'so', 'clear', 'unjail', 'wanted', 'find', 'arrest',
    'booking', 'backup', 'cbackup', 'mdc', 'ticket', 'confiscate', 'radars', 'startradar', 'setradar',
    'handsup', 'frisk', 'leavefaction', 'quitfaction', 'factionquit', 'quitgroup',
    'acceptfaction', 'declinefaction', 'crafting', 'quitjob', 'jobhelp', 'documents',
    'id', 'licenses', 'givekeys', 'takekeys', 'park', 'recovertrailer', 'service',
    'f', 'r', 'd', 'gov', 'megaphone', 'calls', 'servicecalls', 'cancel',
    'firestart', 'firecalls', 'respawn', 'sethome', 'renthouse', 'unrent',
}) do
    markClientCommand(name)
end

--- Admin commands handled on the client (server validates via NetEvents).
Sunset.ClientAdminCommands = {
    setcp = true,
    delcp = true,
    gotocp = true,
    gotoloc = true,
    speed = true,
    coords = true,
    getpos = true,
    pos = true,
    dealershipadmin = true,
    hudexport = true,
}
