# Deploy SunsetMP from Windows (PowerShell)
$ErrorActionPreference = 'Stop'
$Key = Join-Path $env:USERPROFILE '.ssh\sshxodo'
$ServicePath = '/data/coolify/services/b0n1oc2fcrzbgdco838ezm1i'

if (-not (Test-Path $Key)) {
    Write-Error "SSH key not found: $Key"
}

Write-Host "Trying SSH as root (needs authorized key on server)..." -ForegroundColor Cyan
$rootTest = & ssh -i $Key -o BatchMode=yes -o ConnectTimeout=12 "root@193.33.167.216" "test -x $ServicePath/deploy.sh && echo OK" 2>&1
if ($LASTEXITCODE -eq 0 -and ($rootTest -match 'OK')) {
    Write-Host "Deploying via root..." -ForegroundColor Green
    ssh -i $Key -o BatchMode=yes "root@193.33.167.216" "cd $ServicePath && ./deploy.sh"
    exit $LASTEXITCODE
}

Write-Host ""
Write-Host "SSH deploy failed for root@193.33.167.216" -ForegroundColor Yellow
Write-Host "Your key ($Key) works for loadport/blipmade-* but NOT for root." -ForegroundColor Yellow
Write-Host "Coolify sunset files live under $ServicePath (root-only)." -ForegroundColor Yellow
Write-Host ""
Write-Host "Fix (one-time on VPS as root):" -ForegroundColor Cyan
Write-Host "  mkdir -p /root/.ssh && chmod 700 /root/.ssh"
Write-Host "  echo 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMY54ulw+Edb3KPkZVEtObQAOESAP2co3Qy58QRkwMQ Generated By Termius' >> /root/.ssh/authorized_keys"
Write-Host "  chmod 600 /root/.ssh/authorized_keys"
Write-Host ""
Write-Host "Then re-run: .\scripts\remote-deploy.ps1" -ForegroundColor Green
Write-Host ""
Write-Host "Fallback: Coolify panel -> sunsetmp -> Restart (does not git pull)." -ForegroundColor DarkGray
exit 1
