SunsetAdmin = {}

SunsetAdmin.Levels = {
    [1] = 'Helper',
    [2] = 'Moderator',
    [3] = 'Admin',
    [4] = 'Super Admin',
    [5] = 'Owner',
}

SunsetAdmin.Commands = {
    kick = 2,
    ban = 3,
    unban = 3,
    tp = 2,
    bring = 2,
    ['goto'] = 2,
    car = 3,
    dv = 2,
    heal = 2,
    revive = 2,
    noclip = 3,
    god = 3,
    announce = 3,
    setadmin = 5,
    coords = 2,
    hudexport = 3,
    setcp = 2,
    delcp = 2,
    gotocp = 2,
    gotoloc = 2,
    speed = 2,
    dealershipadmin = 3,
    setjob = 3,
    setfaction = 3,
    givecar = 3,
    setleader = 3,
    removeleader = 3,
    acreatehouse = 3,
    ahouseedit = 3,
    astats = 2,
    setstat = 3,
    setjobstat = 3,
    setrob = 3,
}
