local function forward(name)
    RegisterNUICallback(name, function(data, cb)
        TriggerEvent('sunset:nui:' .. name, data)
        cb('ok')
    end)
end

forward('select')
forward('create')
forward('delete')
forward('characterCreate')
forward('characterBack')
forward('chatSend')
forward('chatClose')
forward('chatHistory')
forward('menuClose')
forward('menuAction')
forward('authLogin')
forward('authRegister')
forward('inventoryClose')
forward('inventoryUse')
forward('shopBuy')
forward('shopClose')
forward('atmAction')
forward('atmClose')
forward('garageSpawn')
forward('garageClose')
forward('propertiesClose')
forward('emotePlay')
forward('emotesClose')
forward('clothingApply')
forward('clothingClose')
forward('phoneClose')
forward('phoneSend')
forward('documentsClose')
forward('jobCenterHire')
forward('jobCenterClose')
forward('craftingCraft')
forward('craftingClose')
forward('appearancePreview')
forward('appearanceSave')
forward('appearanceRotate')
forward('appearanceGender')

RegisterNUICallback('hudEditSave', function(data, cb)
    TriggerEvent('sunset:nui:hudEditSave', data)
    cb('ok')
end)

RegisterNUICallback('hudEditClose', function(_, cb)
    TriggerEvent('sunset:nui:hudEditClose')
    SetFocus(false, false)
    cb('ok')
end)

RegisterNUICallback('hudEditFocus', function(data, cb)
    SetFocus(data.focus == true, data.focus == true)
    cb('ok')
end)
