local function forward(name)
    RegisterNUICallback(name, function(data, cb)
        TriggerEvent('sunset:nui:' .. name, data)
        cb('ok')
    end)
end

forward('select')
forward('create')
forward('delete')
forward('characterCreate')
forward('characterBack')
forward('chatSend')
forward('chatClose')
forward('chatHistory')
forward('menuClose')
forward('menuAction')
forward('menuVehicleAction')
forward('menuJobAction')
forward('authLogin')
forward('authRegister')
forward('inventoryClose')
forward('inventoryUse')
forward('shopBuy')
forward('shopClose')
forward('atmAction')
forward('atmClose')
forward('mdcClose')
forward('ticketClose')
forward('ticketIssue')
forward('garageSpawn')
forward('garageStore')
forward('garageLocate')
forward('garageClose')
forward('propertiesClose')
forward('emotePlay')
forward('emotesClose')
forward('clothingApply')
forward('clothingPreview')
forward('clothingClose')
forward('phoneClose')
forward('phoneSend')
forward('taxiRefresh')
forward('taxiEstimate')
forward('taxiRequestRide')
forward('taxiAcceptRide')
forward('taxiCancelRide')
forward('taxiPickup')
forward('taxiComplete')
forward('taxiSetAvailable')
forward('taxiPickMap')
forward('taxiPickPlace')
forward('taxiTip')
forward('documentsClose')
forward('jobCenterHire')
forward('jobCenterClose')
forward('craftingCraft')
forward('craftingClose')
forward('appearanceChange')
forward('appearanceCamera')
forward('appearancePreview')
forward('appearanceSave')
forward('appearanceRotate')
forward('appearanceGender')

RegisterNUICallback('hudEditSave', function(data, cb)
    TriggerEvent('sunset:nui:hudEditSave', data)
    cb('ok')
end)

RegisterNUICallback('hudEditClose', function(_, cb)
    TriggerEvent('sunset:nui:hudEditClose')
    SetFocus(false, false)
    cb('ok')
end)

RegisterNUICallback('hudEditFocus', function(data, cb)
    SetFocus(data.focus == true, data.focus == true)
    cb('ok')
end)
