ALTER TABLE `vehicles`
    ADD COLUMN IF NOT EXISTS `parked_x` FLOAT NULL DEFAULT NULL AFTER `garage`,
    ADD COLUMN IF NOT EXISTS `parked_y` FLOAT NULL DEFAULT NULL AFTER `parked_x`,
    ADD COLUMN IF NOT EXISTS `parked_z` FLOAT NULL DEFAULT NULL AFTER `parked_y`,
    ADD COLUMN IF NOT EXISTS `parked_h` FLOAT NULL DEFAULT NULL AFTER `parked_z`;
