CREATE TABLE IF NOT EXISTS `lssi_exam_reports` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `license_type` VARCHAR(16) NOT NULL,
    `candidate_character_id` INT UNSIGNED NOT NULL,
    `instructor_character_id` INT UNSIGNED NOT NULL,
    `started_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `completed_at` TIMESTAMP NULL DEFAULT NULL,
    `result` ENUM('in_progress', 'passed', 'failed', 'aborted') NOT NULL DEFAULT 'in_progress',
    `theory_score` TINYINT UNSIGNED NULL,
    `theory_total` TINYINT UNSIGNED NULL,
    `checkpoints_completed` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    `checkpoints_total` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    `duration_seconds` INT UNSIGNED NULL,
    `candidate_mistakes` DECIMAL(4,1) NOT NULL DEFAULT 0.0,
    `candidate_marks` JSON NULL,
    `practical_evidence` JSON NULL,
    `review_status` ENUM('pending', 'approved', 'needs_improvement') NOT NULL DEFAULT 'pending',
    `reviewer_character_id` INT UNSIGNED NULL,
    `instructor_mistakes` DECIMAL(4,1) NULL,
    `review_notes` VARCHAR(500) NULL,
    `reviewed_at` TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `idx_lssi_exam_instructor` (`instructor_character_id`, `completed_at`),
    KEY `idx_lssi_exam_candidate` (`candidate_character_id`, `completed_at`),
    KEY `idx_lssi_exam_review_queue` (`review_status`, `completed_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
