-- ═══ STAFF LEVELS (Helper 1-3 & Admin 1-6) ═══
ALTER TABLE `accounts`
    ADD COLUMN IF NOT EXISTS `helper_level` TINYINT(3) UNSIGNED NOT NULL DEFAULT 0 AFTER `admin_level`;

CREATE TABLE IF NOT EXISTS `helpers` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `license` VARCHAR(64) NOT NULL UNIQUE,
    `level` TINYINT(3) UNSIGNED NOT NULL DEFAULT 1,
    `name` VARCHAR(128) NOT NULL,
    `granted_by` VARCHAR(64) DEFAULT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
